
name: AWS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Deploy IaC
        run: aws cloudformation deploy --template-file src/infra/autoscaling_tropo.yaml --stack-name infra-stack

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
